### ISSUE TITLE
Unable to get twitter user public tweets using Twitter streaming API V2

### ISSUE THREAD

**Issue by naser-gulzade** [felixdorn/twitter-stream-api#15]
I want to get real time user tweets from twitter using twitter streaming api v2, I use https://api.twitter.com/2/tweets/search/stream/rules endpoint to set rules with rule like "value": "from:GulzadeNaser" first according to twitter developer api doc, then by calling https://api.twitter.com/2/tweets/search/stream end point to get the real time tweets Unfortunately I could not get the user tweets, but when I add the rule beside above mentioned rule like #demetakalin hashtag, then the mentioned user tweets and other tweets which have hashtag #demetakalin will be on on the result response.

I could get connected with stream, and the connection lives for just 20 minutes or or but when I set the rule to just "from:twitteruseraccount" there is no response, but If I add "#trendinghash" I get the response tweets of hashtag plus "from:twitteruseraccount" tweets too.

I can receive real time tweets using https://npm.runkit.com/twitter-v2. with the same rule set for my account.

This is the rule
 "data": [
        {
            "id": "1555098086317473794",
            "value": "from:1549244593832697856",
            "tag": "all tweets from the user"
        },

Implemented code:
$twitterStream
    ->expansions('author_id')
    ->fields('media.duration_ms', 'media.height')
    ->fields('place.full_name', 'place.geo', 'place.id','place.country','place.name','place.place_type')
    ->fields('user.name','user.id','user.created_at')
    ->listen($connection, function (object $tweet) {
        print_r($tweet);
        //echo $tweet->data->text;
        
        if ($this->received >= 5) {
            $this->stopListening();
        }
   });
Thanks,

**Comment by felixdorn** [comment]
Hey! The stream buffer size (the number of characters gathered before parsing the JSON) was too high (8192, the default socket chunk size), so It worked for high throughput streams but not small ones. I changed it to 85, the tiniest payload length for a tweet. Expect a release today.

**Comment by felixdorn** [comment]
Fixed in the new release (v3).
