### ISSUE TITLE
[DOC] Rulebuilder ->raw('#tag1 #tag2 #tag3') generates exact phrase match

### ISSUE THREAD

**Issue by simonbuehler** [felixdorn/twitter-stream-api#19]
hi,

when passing a string  `#hashtag` to raw it generates `#hashtag` as expected.
passing `->raw('#hashtag1 #another #andso #on')` generates 
`"#hashtag1 #another #andso #on"` which only accepts exact matches. I haven't found out where the logic for that lives and how i can pass in a string e.g. from a form field without the quotes beeing added, any hint would be nice!

**Comment by simonbuehler** [comment]
as a workaround i passed in an array and that worked but i doubt thats the way to handle this

**Comment by felixdorn** [comment]
Hey! Could you copy the output of the following command:

```
composer info redwebcreation/twitter-stream-api
```

Thanks.

**Comment by simonbuehler** [comment]
thanks!
you were right: i was on 1.0.2 and now upgraded to latest (2.1.0) , did the upgrade changes (e.g. no more `exceptXXX`) and now it just works, awesome!

for someone  having the same issues: 
```php
// 1.0.2 old stuff
// $rules->new(tag: 'rule_1')->raw( explode(' ', $validated['rule']))->exceptReply()->exceptRetweet()->exceptQuote()->save();

// new working 
$rules->new(tag: 'rule_1')->raw( $validated['rule'])->isNotReply()->isNotRetweet()->isNotQuote()->save();
```
