### ISSUE TITLE
fread(): SSL: Connection reset by peer

### ISSUE THREAD

**Issue by pickles-kim** [felixdorn/twitter-stream-api#22]
Hi,

When running Twitter Stream API v2, sometimes I get the following error:
```
PHP Warning:  fread(): SSL: Connection reset by peer in /(...)/guzzlehttp/psr7/src/Stream.php on line 231
```
After that, it was able to reconnect after 15-20 minutes.
I'm trying to reconnect by doubling up to 320 seconds with reference to the document below, but it does not work.
https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/handling-disconnections

When I was using Stream API v1.1 with phirehose, the program would automatically try to reconnect, but this library terminates the program when the connection is lost.
Is there an efficient way to reconnect?

And is this a problem on Twitter's side?
Is there anything I can do to prevent this problem?

Please understand that the wording is strange because English is not my native language 🙇‍♂️

**Comment by felixdorn** [comment]
I'm currently on vacation, I'll look at this when I get back. The way it is supposed to run is with a supervisor (i.e cron) that restarts the PHP process when it fails, hope this helps in the meantime.

I'm happy to answer your questions and we'll investigate when I get home.
